### PR TITLE
UPS shipper number and negotiated rates.

### PR DESCRIPTION
**Pull request by bmcdavid**
Added UPS constructor overload for shipper number and negotiated rate property.

### CODE REVIEW

**Comment by dotNetNoob** [comment]
Is the "negotiated rate property" merged into the UPS Provider? If so, how do I set it to true?

**Comment by dotNetNoob** [comment]
Is this project dead?

**Comment by kylewest** [comment]
no

**Comment by kylewest** [comment]
manually merged changes.

**Comment by kylewest** [comment]
Pull request #32 had to be merged manually. It has been merged and released to the NuGet feed as version `0.9.4.51`.

**Pull request closed without merging**
