### PR TITLE
Add INTERNATIONAL_FIRST to FedExProvider service codes

### PR DESCRIPTION
**Pull request by Soulfire86**
This is a fix for Issue #42

### CODE REVIEW

**Comment by Soulfire86** [comment]
Not sure why the AppVeyor would be failing for this. Is this good to go?

**Comment by kylewest** [comment]
merged. will be deployed shortly. thanks @Soulfire86! 

closes #42 

**looking for someone to help maintain this project. please let me know you are interested.**

**Comment by Soulfire86** [comment]
@kylewest sure, I wouldn't mind helping out some more

**Comment by kylewest** [comment]
@Soulfire86 thanks, added you to the repo and to the credits in the readme. shoot me an email kyle at rpmware and we'll make sure you have access to everything and figure out where to go from here.

Kyle

**Pull request merged**
